### ISSUE TITLE
How to change paramters

### ISSUE THREAD

**Issue by mrbot-king** [antontutoveanu/crystals-kyber-javascript#4]
I am trying to change the paramters to Kyber 1024, but I have been unsuccesful, where is the paramaters located so i know what to replace and stuff. Or maybe you have a version for kyber 1024

**Comment by antontutoveanu2** [comment]
Apologies, I’m in hospital at the moment with restricted iPad use. I’ll try add 1024 parameter set as soon as I can.

**Comment by antontutoveanu2** [comment]
not suicide

**Comment by antontutoveanu** [comment]
kyber 1024 is now available

use via K1024_KeyGen, K1024_Encrypt, K1024_Decrypt functions in kyber1024.js
