### ISSUE TITLE
Encrypt function: convert kr to kr_str should be an Array of 64 bytes intead of 32 bytes

### ISSUE THREAD

**Issue by flatorre1** [antontutoveanu/crystals-kyber-javascript#6]
Hi and thanks for your great work! I would like to contribute to improve your code.
I see these lines in the code:

```
    let kr_str = hash3.digest('hex');
    // convert hex string to array
    let kr = new Array(32);
    for (i = 0; i < 64; i++) {
        kr[i] = hexToDec(kr_str[2 * i] + kr_str[2 * i + 1]);
    }
    let kr1 = kr.slice(0, 32);
    let kr2 = kr.slice(32, 64);

```
But because you are adding 64 bytes to the kr array, it should be created as
`let kr = new Array(64);`

In fact, you can get the digest value directly in bytes instead of getting it as a hex string, saving the conversion in the hash function from bytes to hex string and also the conversion from hex string to bytes in your code:
```
    let kr = hash3.digest();
    // console.log('kr length = ', kr.length); // <- it prints 64
    let kr1 = kr.slice(0, 32);
    let kr2 = kr.slice(32, 64);
```

Best,
Fernando.

**Comment by antontutoveanu** [comment]
Good spot. I have updated the code. Thank you very much.
