### ISSUE TITLE
Using shared secret - aes - how?

### ISSUE THREAD

**Issue by xellDart** [antontutoveanu/crystals-kyber-javascript#7]
Hello, I am testing using Kyber, but I have a couple of questions, in the diagram shown what I understand is the following:

The server creates the key pair using K768_KeyGen();
The pk is sent to the client and it generates a shared secret and a cipher text.

The cipher text is transmitted to the server so that it decrypts using the private key and obtains the shared secret.

Client and Server have the shared secret.

Then the AES 256 algorithm is mentioned, **how would it be applied** if this algorithm generates two leads, if this algorithm uses a key and an iv for encryption and decryption?

**Comment by antontutoveanu** [comment]
The diagram illustrates a basic end-to-end construction to show the simplest functionality of the key exchange. There are more complex protocols in design that provide more security properties. I am still researching but here is the best place to start.

The shared secret between the client and server is used with AES symmetric encryption/decryption processes as a key. IV is generated by the AES implementation and usually appended at the front of the AES ciphertext (it is not the same as the key).

I recommend AES-GCM mode (known as an AEAD) for symmetric encryption.

You can view the code for an end-to-end implementation I put together available here:
https://github.com/antontutoveanu/E2EE_Protocol

**Comment by antontutoveanu** [comment]
High-level AES-GCM functionality
<img width="828" alt="aes-gcm" src="https://user-images.githubusercontent.com/28477472/178089640-1eecee0c-fdd9-4a4a-a3b3-e793e547796d.png">

Note: IV can also be known as 'nonce'.
